### ISSUE TITLE
[BUG Report] XXX

### ISSUE THREAD

**Issue by nao1215** [nao1215/rainbow#48]
## About the problem
When the s3hub command deletes an S3 bucket, the deletion of the S3 bucket fails because there are still S3 objects remaining.

```shell
$ s3hub rm abcdef-test-dev
CHECK: delete abcdef-test-dev with objects? [Y/n] Y
 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (7/7, 129 it/s)        
delete 7 objects in pogo-test-dev
operation error S3: DeleteBucket, https response error StatusCode: 409, RequestID: MZ5QP0YRHY4C1GJW, HostID: XxZm4SSyKXDdet528dYQoTmETab8Bb+YL/E0MJx2Oy5qf8AQywZ567nnGgZS1VHzfKRt7DH7Qm4=, api error BucketNotEmpty: The bucket you tried to delete is not empty
```

## Expected behavior
s3hub delete s3 bucket with s3 objects.

## Steps to reproduce
1. Create S3 Bucket below setteing:
```yml
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: "sample-ucket-name"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionExpiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 45
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

## Environment
- OS: macOS 13.6.3 22G436 arm64
- Command Name & Version: s3hub v0.0.0-20240129222627-9f1107059334 (under MIT LICENSE)
